### ISSUE TITLE
Nested maps and lists in group metadata

### ISSUE THREAD

**Issue by apeteri** [coreos/terraform-provider-matchbox#10]
I experimented with modifying the simple example by adding a second SSH key to the metadata section (only changed parts are shown below):

**terraform.tfvars**

    ssh_authorized_keys = [
        "ssh-rsa <first-key> user@host",
        "ssh-rsa <second-key> user2@host",
    ]

**variables.tf**

    variable "ssh_authorized_keys" {
      type        = "list"
      description = "List of SSH public keys to authorize"
    }

**groups.tf**

    // Match machines which have CoreOS installed
    resource "matchbox_group" "node1" {
      name    = "node1"
      profile = "${matchbox_profile.simple.name}"
    
      selector {
        os = "installed"
      }
    
      metadata {
        ssh_authorized_keys = ["${var.ssh_authorized_keys}"]
      }
    }

However, when running `terraform apply`, the following error message is displayed:

    * matchbox_group.node1: metadata (ssh_authorized_keys): '' expected type 'string', got 
    unconvertible type '[]interface {}'

Is it possible to extend the set of supported types for metadata values?

**Comment by dghubble** [comment]
I've looked into this quite a bit and it relates to what the terraform "type system" can represent.

Matchbox [Groups](https://github.com/coreos/matchbox/blob/master/matchbox/storage/storagepb/group.go#L149) themselves accept `map[string]interface{}` metadata (you may have a key `ssh_authorized_keys` and value be a list of strings and use full Go templates in Container Linux config templates). In writing a Terraform plugin for matchbox, every Terraform resource has to be a Terraform schema type. Group.metadata is defined as `Type: schema.TypeMap, Elem: schema.TypeString` so only a map of strings is allowed. https://github.com/coreos/terraform-provider-matchbox/blob/master/matchbox/resource_group.go#L36.

We did not find a way to accept a map of interfaces with the available Terraform schema types. https://godoc.org/github.com/hashicorp/terraform/helper/schema#Schema.

Eager to hear if anyone has a solution. For now, Terraform users of matchbox can only use flat maps of metadata, not the usual nesting options.

**Comment by apeteri** [comment]
Right, some of the existing non-Terraform examples can already handle a list of SSH keys in the Ignition template. Are any string/list manipulating functions available while those are rendered? I might be able to get away with joining the list to a delimited string in Terraform, then splitting it back to individual items at rendering time.

**Comment by dghubble** [comment]
Yes, you'd probably need to do that templating on the Container Linux config in Terraform, before creating a profile. The downside then is that profile is fixed with that set of ssh keys, but maybe you're ok with that.

It gets at two different strategies: having a single profile to represent say "k8s-worker" and the groups inject the bits that are unique to each node or in terraform create a different profile per node by templating earlier and reducing the use of groups for templating. Either is valid and in Tectonic the approach is still evolving. https://github.com/coreos/tectonic-installer/issues/693

**Comment by dghubble** [comment]
For now, the approach in terraform-based Matchbox examples has been to keep templating fairly simple.

The Kubernetes cluster example only allows one ssh_authorized_key too. https://github.com/coreos/matchbox/blob/master/examples/terraform/bootkube-install/README.md

**Comment by apeteri** [comment]
Thank you for taking the time to expand on the alternatives!

**Comment by TerraTech** [comment]
@apeteri, I'm faced with this very issue right now.  Did you find a workaround to inject multiple ssh keys without hardcoding them into the template?  My current workaround is to use ```raw_ignition``` in the matchbox_profile, built up from the ```ignition_file``` provider.  However, as the profiles have evolved, I've found that I need to create separate configs for each node via templating.  Unfortunately going the pure raw_ignition route blocks my ability to process template directives.  :(

Overall, this is a deficiency of terraform itself, that really should be addressed, unless matchbox can find a creative solution to work around the limitation.  At bare minimum, matchbox_group metadata should be able to pass in both strings and lists.  Maps would be nice to, but those can be reduced down to passing in the keys you need via strings.

**Comment by apeteri** [comment]
@TerraTech, I ended up using a single service account, so don't really have any workarounds. 😐
