### ISSUE TITLE
Data source documentation

### ISSUE THREAD

**Issue by apeteri** [coreos/terraform-provider-matchbox#15]
The Tectonic installer uses composable data sources that together make up an Ignition config: https://github.com/coreos/tectonic-installer/blob/master/modules/aws/ignition/ignition.tf

This feature looks very useful, as I'm currently trying to do the same thing with Terraform's template provider, with limited success. 😄 Do these come from the matchbox provider? Is there any documentation available for them?

**Comment by dghubble** [comment]
The raw Ignition data source is not part of Matchbox or this plugin. Its something in hashicorp's terraform source.

It is recommended you write [Container Linux Configs](https://coreos.com/os/docs/latest/configuration.html) to declare how your machines' should be provisioned. You can find the relevant [docs](https://github.com/coreos/matchbox/blob/master/Documentation/container-linux-config.md), [examples](https://github.com/coreos/matchbox/tree/master/examples), and some Terraform [modules](https://github.com/coreos/matchbox/tree/master/examples/terraform/modules) using this approach. Container Linux Configs are converted to Ignition by Matchbox or as an internal detail (in future).
