### ISSUE TITLE
SSH Authorised Key as list

### ISSUE THREAD

**Issue by TimJones** [coreos/terraform-provider-matchbox#19]
I'm coming from a manual matchbox config to use a terraform-provisioned config but it seems that only one SSH auth key is allowed at a time. It would be nice to support the multiple SSH keys allowed by the groups JSON.

**Comment by dghubble** [comment]
This has been discussed quite a bit in #10, please see that issue.

Matchbox [Groups](https://github.com/coreos/matchbox/blob/master/matchbox/storage/storagepb/group.go#L149) themselves accept `map[string]interface{}` metadata (you may have a key ssh_authorized_keys and value be a list of strings and use full Go templates in Container Linux config templates). In writing a Terraform plugin client, every Terraform resource has to be a Terraform schema type. Group.metadata is defined as Type: schema.TypeMap, Elem: schema.TypeString so only a map of strings is allowed. The Terraform type system does not currently allow a map type of interface values.

This provider is limited by what the Terraform "type system" offers.
