### ISSUE TITLE
package context: unrecognized import path "context" (import path does not begin with hostname)

### ISSUE THREAD

**Issue by urzds** [coreos/terraform-provider-matchbox#5]
I am unable to install the Matchbox terraform provider using Go:
```
# go get -u github.com/coreos/terraform-provider-matchbox
package context: unrecognized import path "context" (import path does not begin with hostname)
# go version
go version go1.6.2 linux/amd64
```

**Comment by urzds** [comment]
Works with Go 1.8.1. Maybe the minimal version should be set in the build scripts?

**Comment by dghubble** [comment]
Yes, terraform v0.9 seems to require Go 1.8 so it would be good to enforce that

**Comment by dghubble** [comment]
Docs mention developers need Go 1.8+ and there are release binaries for non-developers. Closing.
