### ISSUE TITLE
context deadline exceeded

### ISSUE THREAD

**Issue by Quentin-M** [coreos/terraform-provider-matchbox#6]
When matchbox cannot be reached, the error that is bubbled up in the TerraForm CLI is not clear:

```
module.tectonic.data.template_file.tectonic-rkt: Refreshing state...
module.tectonic.data.template_file.tectonic_service: Refreshing state...
module.tectonic.data.template_file.tectonic: Refreshing state...
module.bootkube.data.template_file.bootkube: Refreshing state...
module.bootkube.data.template_file.bootkube_service: Refreshing state...
module.bootkube.data.null_data_source.etcd: Refreshing state...
Error refreshing state: 1 error(s) occurred:

* context deadline exceeded
```

There is even no indication that the matchbox provider attempted to run.

Only when we enable the debug logs, we can read:
```
2017/04/25 14:59:00 [DEBUG] plugin: installer: 2017/04/25 14:59:00 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: dial tcp: lookup matchbox.example.com on 172.31.18.80:53: no such host"; Reconnecting to {matchbox.example.com:8081 <nil>}
```

**Comment by dghubble** [comment]
Actually, its simpler than I suggested, no call needs to be made. In the Matchbox gRPC `client` package, `New(config *Config) (*Client, error)` blocks and dials the endpoint to get a `*grpc.ClientConn` which is re-used by the Client. We're already setting the timeout to 30 seconds and the error being returned in "context deadline exceeded".

I'll spruce up the error message.
